version: '3.8'

services:
  dashboard:
    # 构建镜像（使用当前目录的Dockerfile）
    build: .
    
    # 容器名称
    container_name: docker-dashboard
    
    # 端口映射（主机端口:容器端口）
    ports:
      - "8080:80"
    
    # 重启策略：除非手动停止，否则总是重启
    restart: unless-stopped
    
    # 环境变量设置
    environment:
      - TZ=Asia/Shanghai  # 设置时区为中国
    
    # 标签，方便管理
    labels:
      - "com.docker.compose.project=dashboard"
      - "com.docker.compose.service=dashboard"
    
    # 资源限制（可选）
    deploy:
      resources:
        limits:
          memory: 128M  # 最大内存使用128MB
        reservations:
          memory: 64M   # 最小保留64MB内存
    
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# 网络配置（可选）
networks:
  default:
    name: dashboard-network
    driver: bridge

# 数据卷（如果需要持久化存储配置）
volumes:
  dashboard-config:
    driver: local